format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/atmosphere/restart_dump.astart
  hashes:
    binhash: 1ad16a9be4afc836628aff8bcc2f7f1b
    md5: 9c9fe48ccb173f3233c8688cc3ed91d8
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/atmosphere/um.res.yaml
  hashes:
    binhash: b3be3566329fb1748bfbec3f02c165e1
    md5: 4a3fa795377091507eaacc9a60e885d9
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/coupler/a2i.nc
  hashes:
    binhash: 7711056ae8ac97f1f6b624a2395d816c
    md5: 534b9c515ed461c24e5892e5c716dbaa
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/coupler/i2a.nc
  hashes:
    binhash: 74a89f847f70e26e164d94f8981f1f05
    md5: 51a88341472d2ace1ee8f66d0b8605fd
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/coupler/o2i.nc
  hashes:
    binhash: bd0339714d393c1937a70dd1aac69e9c
    md5: 0038f97f7b2f545b03d85862e39c2b88
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ice/cice_in.nml
  hashes:
    binhash: 54e4375ee8cb82bcd12520a662b038e0
    md5: 31cc3bb31b27537fd8d63b1877e75640
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ice/ice.restart_file
  hashes:
    binhash: daa7d54b952a134d3eca9ffc48c377b8
    md5: d80637c9d1adb43417eb7bf526517499
work/ice/RESTART/iced.18660201:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ice/iced.18660201
  hashes:
    binhash: 0fd5c9aae1c62ddd57da913e7e817b5f
    md5: 6132f58efe91d68a43e1ddf96b59f0df
work/ice/RESTART/iced.18660301:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ice/iced.18660301
  hashes:
    binhash: 9bfff5d234e860ae6a88bf7703afac42
    md5: 06fd52b8f70f2c69ea8a65f27df499b6
work/ice/RESTART/iced.18660401:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ice/iced.18660401
  hashes:
    binhash: b9b1ba86e30096a02536179d9c7983dc
    md5: 3787214e7db37a3c488ce3179ef89114
work/ice/RESTART/iced.18660501:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ice/iced.18660501
  hashes:
    binhash: c6dab3a14c688f887521638552f27482
    md5: 464ba818e1621a7f842ef30e9b05ec9c
work/ice/RESTART/iced.18660601:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ice/iced.18660601
  hashes:
    binhash: bdf727aec426969c8a47ece092c79ce9
    md5: 7b157c894b1ce4abb60971dcd128a6f5
work/ice/RESTART/iced.18660701:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ice/iced.18660701
  hashes:
    binhash: 1c2010c3ae118ba40676d7248f480e94
    md5: 470ce5678c13124d916093650d33cf1f
work/ice/RESTART/iced.18660801:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ice/iced.18660801
  hashes:
    binhash: 627b6eb8f5a4037752cde37329bb54be
    md5: d0e735c3cdc976858f371b50864fae80
work/ice/RESTART/iced.18660901:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ice/iced.18660901
  hashes:
    binhash: 15a85bf76ca320fa4a4c8d33da7efefe
    md5: 8d5c41c1f400d995146514a5df3b2459
work/ice/RESTART/iced.18661001:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ice/iced.18661001
  hashes:
    binhash: cc6ff079abccddccda815cb00a04070a
    md5: 2a8fef65cfdded3557dd7b90bc8cdba2
work/ice/RESTART/iced.18661101:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ice/iced.18661101
  hashes:
    binhash: 5667d315f8add4a9e28a5567b1169835
    md5: a1e83f6395fd9f469b46d6311d8c685d
work/ice/RESTART/iced.18661201:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ice/iced.18661201
  hashes:
    binhash: 41d98138c1cfd8e211084d1e0a9b928a
    md5: 91f8357f6fa2f61e3fe365a8f616b53f
work/ice/RESTART/iced.18670101:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ice/iced.18670101
  hashes:
    binhash: f289093ad546e570bdf8752ad810ee93
    md5: 249ef4bd2835f0557d3b7e6d189f1266
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ice/input_ice.nml
  hashes:
    binhash: fa3570459fa1383b18911a9ee931328a
    md5: 3edb68db1184e4eef27c87bdfe7d5ec2
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ice/mice.nc
  hashes:
    binhash: cfddbfc14b1b44a1ae7d8003970c1794
    md5: 21bb93ee594eba0dabeebfecf69d482c
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ocean/csiro_bgc.res.nc
  hashes:
    binhash: f6949f6d088409ac7e5b35b5e7e91eb9
    md5: e8a867ec98367976ab9787a982ca68da
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 219a54f91f16c314d2c91e8b0fcb3545
    md5: d87c79b5b470c9efad308e9cfd860d7f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ocean/ocean_age.res.nc
  hashes:
    binhash: 01d557a3a0668bfbf27732757cdaeabc
    md5: ed41e162285e6ff0eb856ba2fd252523
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 75c7af7c4a822f231cc37471d4a45697
    md5: b6822f84a9541a1141bc9ac36a87fea5
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a3a7ee755034278e568c3cbca4cb4c88
    md5: 2147df05fb6dddc285099c3c47be3940
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ocean/ocean_density.res.nc
  hashes:
    binhash: a6c713b78a5d688f5cb97d5f264af879
    md5: 045e0ce8d86e18c418d9a1f1740582ae
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b058169e79ccd6e23740dc14dc17cab6
    md5: cffeb5a628b325422c3cd2037cb8c662
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 37c005266b3e060c8525e1bed5c51bd1
    md5: abb8b72bc6a4dc11132b1e4dbfc53688
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 840b5725b23873840c90922e830920bc
    md5: 9451487adb1498d389dead5e42d79214
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 40b45b229496c6121a585efb64ba3700
    md5: 229028a975be9890705665ac27ed26ba
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4f8dfc070222644d8a00923045feaaf7
    md5: c848d72d384e0ca74c81564766ee4727
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 6deeab0949be3402f979b2697553a217
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ocean/ocean_solo.res
  hashes:
    binhash: a4012a4924967c1052904047a36bcdf3
    md5: b23925432d12541e0ab5ab5f3e9fae1d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 170fdf4ff40fba043c22c8ac6e25201d
    md5: dc8bf40064655d6285be23abcd9e050c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d14a7426b3f621a1c527d67ea971acb2
    md5: 76d050ee5cf5c9873b3a6575f5af91b9
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ocean/ocean_tracer.res
  hashes:
    binhash: 375ce66482087a9c93924a71ca6fb55f
    md5: 3b9898fc4a213c3738e7e9557daddafa
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ocean/ocean_velocity.res.nc
  hashes:
    binhash: edc6218adbc4e4b3973112d708f0c9e1
    md5: c4fb2932d7b26ce16356d40cd33e909f
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart017/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 99eb34b654d0debca4a13ebf8b7298ca
    md5: 69d8214a49b96c69554802d8cd52210d
