format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/atmosphere/restart_dump.astart
  hashes:
    binhash: c3286984ac8fc0f9d4a7146113cdbbdd
    md5: 9a8bfc0c8afad4599e9fc2fbdc740c60
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/atmosphere/um.res.yaml
  hashes:
    binhash: a929e1ca78ffbc33de96973e131849f8
    md5: de7fa459a1d589ef063ff66e33b33c9a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/coupler/a2i.nc
  hashes:
    binhash: 50eb419bb2a12dd6d508120f9a537908
    md5: bad2b8d4015e5af49b84c551fe442e88
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/coupler/i2a.nc
  hashes:
    binhash: 0a1073cd228302ec1beaa8f853b76738
    md5: b85f07cf109e3ae22b99da493c4c0201
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/coupler/o2i.nc
  hashes:
    binhash: ca8844ab278cc7eb590d4ede5a6db39c
    md5: 15f48b02c4a9c436cee2500b03387691
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ice/cice_in.nml
  hashes:
    binhash: dd775b5a889b83bb984da7d843bb0f97
    md5: 514235fdf2910dd93e651ee3ca19a08d
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ice/ice.restart_file
  hashes:
    binhash: 63442f7c0937016a2119038b884d5a88
    md5: 37ab73e80b9586527453055be1b60919
work/ice/RESTART/iced.18670201:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ice/iced.18670201
  hashes:
    binhash: 0fa5af64f842da7336facad9b94f698e
    md5: 296c692c7a4522fee7dc4938aeb5bf7f
work/ice/RESTART/iced.18670301:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ice/iced.18670301
  hashes:
    binhash: d0d4ccea35d34290c0860e5485bd1389
    md5: b66a288e01f1b8e75ec306b59f1ed204
work/ice/RESTART/iced.18670401:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ice/iced.18670401
  hashes:
    binhash: 1ec1f101e4ada24b4e27a30b99edf1ab
    md5: 4c0155cbb87f2a592333a55b726212a8
work/ice/RESTART/iced.18670501:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ice/iced.18670501
  hashes:
    binhash: 9c6d368dc3b8087506035169cfb2b222
    md5: c00b9bb08945a2b3cfc239e8f16399da
work/ice/RESTART/iced.18670601:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ice/iced.18670601
  hashes:
    binhash: 728de3d6b167d06ea054076da5b46402
    md5: 819f99673e2b8e38e1d7a8719688b640
work/ice/RESTART/iced.18670701:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ice/iced.18670701
  hashes:
    binhash: 3ca440c66d38151f067590bd42f87431
    md5: 2a2052b2bcf3e08a8bba39c3e183801a
work/ice/RESTART/iced.18670801:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ice/iced.18670801
  hashes:
    binhash: 5a69a8ebe55a8a7c4715c8594913be8c
    md5: 42bda8695522d5f487148d9247aec0a6
work/ice/RESTART/iced.18670901:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ice/iced.18670901
  hashes:
    binhash: 3883be00023085ad16673969b57201c3
    md5: 57e222c1d5c6a6c2bd704fce3811be38
work/ice/RESTART/iced.18671001:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ice/iced.18671001
  hashes:
    binhash: de3390abd04cb7d2f2e787de026aced2
    md5: 5cdf1c7e0a1ba51287c905085011a657
work/ice/RESTART/iced.18671101:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ice/iced.18671101
  hashes:
    binhash: cd7aed851bccf3d61921f54d1713327f
    md5: 6f3326e4859f71d601866ae997180267
work/ice/RESTART/iced.18671201:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ice/iced.18671201
  hashes:
    binhash: 2607aed06b7124f25269dfeea54ee0a0
    md5: 8e3050f744452eda735839138eba18fb
work/ice/RESTART/iced.18680101:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ice/iced.18680101
  hashes:
    binhash: 152c596a2f52d5cde1190eafee06e7d7
    md5: 051ca121c82bc496c6e2374080b16486
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ice/input_ice.nml
  hashes:
    binhash: 6528e67092008c6f993ed2e4fff734fe
    md5: a37e7cfe12be57d148c60266399fac09
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ice/mice.nc
  hashes:
    binhash: 87443ec529be523cff5a06d8f5c127fc
    md5: 852c2f388f79e27d3ee7a934954017e8
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ocean/csiro_bgc.res.nc
  hashes:
    binhash: 361a09f5e8957924cc172644f018eae9
    md5: 27ffca07744f56d605afdf822e6e2175
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 6031d975df41b35e625366af35a4dd59
    md5: 29898398093bd614b16a1fc11809b2cf
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ocean/ocean_age.res.nc
  hashes:
    binhash: 948404e7f269a34ce64c40bca565138e
    md5: 248175595e37a4a1f7fcaaf88022d184
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ad4a80ffba44fdb3150247a21d0412f1
    md5: 8ff1809b98d5fd83ac2e957e9e8e4b74
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 370da76b01bad0c253974c56c8d69789
    md5: 16f2992e0c8e1c32720e9bfe464a88f1
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ocean/ocean_density.res.nc
  hashes:
    binhash: 27c773d0584cc98c069c4ef10e222d14
    md5: 6ed36067e31fba93244d9241a77da00f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d3db65f006869381e73b4c5f57518e29
    md5: 415794e906ea0b828fb8ec5711e98d9d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 789fff1037e8e10385dd2cb7bb587991
    md5: 3e815a6272bcdb5e6d95fa5d45cf5b92
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4631396d2ad44f2a27c8a13727ac49d2
    md5: 5c0c3405ed1c7d3e75a2954b6f69a9ac
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d2367ac4397bab9a08c0cf4abdafe13a
    md5: fe52fe07dd77e5ad6ce4c01ac4df9287
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 1b25a0bbf87c19a75abed82f30e288f1
    md5: 00eeeb1a0cd8a437ca12d381341dd90c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 06b466b1bb0f962ec889402810a2e1a5
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ocean/ocean_solo.res
  hashes:
    binhash: e6fa8d00319c5608c022f46980a6c299
    md5: 3aa39035e9c7e193f556265e61004b48
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 317a2ec1a8a6644a062062083271ab1a
    md5: 53288ee69e0344f0a95b0decdb1523ae
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ceae9651c6bd5dce660fe599688279d0
    md5: 09c6ebc022a263489b69e653ad0db325
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ocean/ocean_tracer.res
  hashes:
    binhash: ab66baf9ad0d1021c71a2c5793625de1
    md5: 70b608861a42e6ecb7e76f95975509e3
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 720c84ff402fe21b8bf40f8b98914590
    md5: 0c74fc4c55869bb638cde9e6dc8361c9
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart018/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 09264ba0b8ece4cadcb195f928f820a2
    md5: aa0a82d64a5181791a5ba573da42b0f7
