format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/atmosphere/restart_dump.astart
  hashes:
    binhash: bed5709c4822967dc8179d438ea87e46
    md5: b112375cf7e7c3e06e6d2a7a440b3ef2
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/atmosphere/um.res.yaml
  hashes:
    binhash: b505b3a7320c7b7c723a8937638ce2dc
    md5: e961128274bcc4b862d7d718533e34d6
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/coupler/a2i.nc
  hashes:
    binhash: 35d43b02dbf7e1d9dc5ff3ccb0e02c4a
    md5: 08d13873b818e0db2b908c8a8b63d798
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/coupler/i2a.nc
  hashes:
    binhash: 9b0b0070b47be2e31ad1e84d8f78c0b3
    md5: d520a45c0ce6ef06cef7260c79703fcd
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/coupler/o2i.nc
  hashes:
    binhash: 409f7c2e0c8f6e6481836f2d797898d8
    md5: bccf8b1a3b8de06f0365d954ad4f8616
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ice/cice_in.nml
  hashes:
    binhash: 68765ff0ddecd4ffd866a621c92d4974
    md5: 821bef0ab81588bbcce2a9d67bb67ed4
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ice/ice.restart_file
  hashes:
    binhash: f9cbe3d91f7f707f1690c02103ae0cfa
    md5: a81cf5d34a6eb42f6f50076d0831ff1f
work/ice/RESTART/iced.18610201:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ice/iced.18610201
  hashes:
    binhash: 41e2eed5ccd28abf125fb5601390d4e8
    md5: 391dbded7f0f87d9ad757e74dbea0177
work/ice/RESTART/iced.18610301:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ice/iced.18610301
  hashes:
    binhash: f38c905df2cb0aaf5a2872c5ace61186
    md5: 4789fe7fe883cbda7b82508c1fc06da3
work/ice/RESTART/iced.18610401:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ice/iced.18610401
  hashes:
    binhash: f30c3b5bd085128f9a02cd4f06fd858c
    md5: 70ffa7bcfe1e771cdc53a7fae13e3ea3
work/ice/RESTART/iced.18610501:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ice/iced.18610501
  hashes:
    binhash: 62b7ea065f7bf47eb5498cb2d09d85a6
    md5: 3b172cbe52aad4c12db1915f2486c090
work/ice/RESTART/iced.18610601:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ice/iced.18610601
  hashes:
    binhash: 701dd61b77dd2a6c80590f72b5cf45cd
    md5: 51891bc95147e9aa491ba121480835dd
work/ice/RESTART/iced.18610701:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ice/iced.18610701
  hashes:
    binhash: 84d61492567398c619212e5717028d22
    md5: 36f6f3ea07a9477f52a1a733fe3909c7
work/ice/RESTART/iced.18610801:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ice/iced.18610801
  hashes:
    binhash: dd9fcdc77e69fabdc0b9894cc9ec4815
    md5: 8f9981fb186a8a8698b39f9c0c624174
work/ice/RESTART/iced.18610901:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ice/iced.18610901
  hashes:
    binhash: 4a2b1195e2fc57837a875de0e4cffe1e
    md5: 05bdca738686afc05ec7b49bfbcb9e7b
work/ice/RESTART/iced.18611001:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ice/iced.18611001
  hashes:
    binhash: f34a99aa96641eb286ddd1571b6c58cf
    md5: d879250d1e0dea93605a4e5e829d179d
work/ice/RESTART/iced.18611101:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ice/iced.18611101
  hashes:
    binhash: 16ba5530ae8b9f2d493d1c582296b7fc
    md5: 005adcf3fcd97408f8c544c88e9f1ffb
work/ice/RESTART/iced.18611201:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ice/iced.18611201
  hashes:
    binhash: 5b56bcace5f250011563dc204491d4b4
    md5: 388bc6d01b1a60abf85e2fa00e318521
work/ice/RESTART/iced.18620101:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ice/iced.18620101
  hashes:
    binhash: c4886044f0e7973a39fee679403abfb9
    md5: 78a9f88fae300a2a3337e32c7e3c95d1
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ice/input_ice.nml
  hashes:
    binhash: 578a806b09872ae584bafaa7c736e3ba
    md5: a7ecb7373e3d20fd4f298de6fd858a57
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ice/mice.nc
  hashes:
    binhash: c9dcd09529227ad8525099bb107c67cb
    md5: 1b66ae113a8bcac2b573fddcb8d5247e
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ocean/csiro_bgc.res.nc
  hashes:
    binhash: 6c9ed51c77149fbabe7ee133e36557e2
    md5: 1964315974cf5f82410857466933b3f7
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 5097881795db12894b8224492d4b55ad
    md5: 0a739a45cb3113633f4d9c500ea1bfbd
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ocean/ocean_age.res.nc
  hashes:
    binhash: d95450d108c733ed0eb14ac40174ded5
    md5: 819edce9b8f325527a98ac01d25e0c1d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 9ad02ce8244dd30a9f65ee2649bac0a2
    md5: 938ae18412617f3fea024edb9a2d2005
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 0671ad81d3a71b1fa8ce0be18422861d
    md5: 48b02a54cd0a8d53f7b89cab9bf8e478
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ocean/ocean_density.res.nc
  hashes:
    binhash: e16d10d0041ff2e9e18a29345f210756
    md5: 8807c7d6d248910a4e3fd3649eeaa1d4
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f8f8a454079542cd162726471b7cda24
    md5: 90963e0facf3f645ed0d02a85976586b
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1746d9964855c708df9f2f928cc073d7
    md5: b2cb87ea59a73be060b3afba6503f421
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 136920b775b6059e4ba22ad0a276dfb6
    md5: 3cd491d52f5a443e3724cfa921bf432a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 39bb265d12800071ad4f8e6a02e14fa7
    md5: 52d59ba76ae8877b570255d717c2590d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c86735aa712b80e27e0e7bc9cb8595fe
    md5: a24db0f7235a57ff79a53ff6cf5968a6
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b77198c3e2ee318f5c91c3134674f349
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ocean/ocean_solo.res
  hashes:
    binhash: 416b1b44b27962e56cd47a8fc6791a27
    md5: 1abc90c2b69a3a179d19fee617df382f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 0fb48c0b86b358b044a74e686d2598c9
    md5: 02b67b1e2a1e55b66d3df429c8daceec
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 1d150deb4748499fed3c2697247afecd
    md5: 095c9d60fc0b230b1e790d0815886515
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ocean/ocean_tracer.res
  hashes:
    binhash: 86c801de6184d526b6382200461397c8
    md5: 5b85a47e559fbf0816a5f180b3d3945e
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 62551707ef6d2df8f38e2b0fc41b017f
    md5: 35c8a0afd580aa6e9e207bb618dcf846
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart012/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ded8619c1929fd2c3f1ad2e3bc91691d
    md5: 8b9ff678de18383c29e03e5207dde386
