format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/atmosphere/restart_dump.astart
  hashes:
    binhash: b2fded40d9cca0ad25848e88636d4425
    md5: eab43495326035516b24597945b37604
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/atmosphere/um.res.yaml
  hashes:
    binhash: 99c715fe8200c2dcd1695cbff4d4f709
    md5: e54bff03f949819557b4142ead42fe08
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/coupler/a2i.nc
  hashes:
    binhash: 03848f7bffb801346455e18fe0639e8b
    md5: 030a3c004a1d9b3f287e3165ce169b88
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/coupler/i2a.nc
  hashes:
    binhash: 5171fe414af132213867ba1c0ff17f22
    md5: acf937dbb61876f977ed001fca7f42be
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/coupler/o2i.nc
  hashes:
    binhash: 46bf4b0562c0e0591d4eb8d863e75557
    md5: d55670f6dadf5dadb7f4b00228780f99
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ice/cice_in.nml
  hashes:
    binhash: e56a5d495fe1a3841a7b3055cbd95ef2
    md5: 5f6379672f61c7a16aa101d5e47041be
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ice/ice.restart_file
  hashes:
    binhash: ac5e7e1ff19842486924f22fa0240128
    md5: d68f15ae07a4003a6fe237633f3e2b96
work/ice/RESTART/iced.18530201:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ice/iced.18530201
  hashes:
    binhash: be090528d1d39315186d20c8cea7eb7c
    md5: 8ca0d87d41b3ad9812ec94272c95a5c8
work/ice/RESTART/iced.18530301:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ice/iced.18530301
  hashes:
    binhash: d7e85ea36a3c7a1cd4fdb6e6d3e01831
    md5: f1f690c6545d8fa95f575f2c76082dfa
work/ice/RESTART/iced.18530401:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ice/iced.18530401
  hashes:
    binhash: e7c7e158af0ce4d47a69ffdb7b54c1cc
    md5: fe1234e38d2d5b1701fb295aa1b2bfa8
work/ice/RESTART/iced.18530501:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ice/iced.18530501
  hashes:
    binhash: 837a44d3d3e6d52b9ce30208aefc993c
    md5: 04076907969f1fa73c1c596352721436
work/ice/RESTART/iced.18530601:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ice/iced.18530601
  hashes:
    binhash: 2f8d0d1438c85a478d782456248641c6
    md5: f0fb9734df739653c0eb25c24cf27088
work/ice/RESTART/iced.18530701:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ice/iced.18530701
  hashes:
    binhash: c019752988a42f3d149fc984530c63a6
    md5: 8093a42952524730abadc353a2980c1a
work/ice/RESTART/iced.18530801:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ice/iced.18530801
  hashes:
    binhash: a5415d1e4e46cccf75bb68ec2705c33c
    md5: ea70e9d3931bbb12dde31266c52e96e0
work/ice/RESTART/iced.18530901:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ice/iced.18530901
  hashes:
    binhash: c56a069f8bff65ca2672068a6dbf160b
    md5: a640a4ad3e0de5bdfe31283d3f6fb7de
work/ice/RESTART/iced.18531001:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ice/iced.18531001
  hashes:
    binhash: c786c88afd1091f613c036c90940438d
    md5: 568aa5795ecb1cecfccc117c7804171b
work/ice/RESTART/iced.18531101:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ice/iced.18531101
  hashes:
    binhash: 9ad64d1289a651511d47d3a0d8156fde
    md5: ef73910d6d2f1abb7cf5e1a57e52660f
work/ice/RESTART/iced.18531201:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ice/iced.18531201
  hashes:
    binhash: 5a0c7243e5a7606e2efa2ac3200c5adf
    md5: 1a1171b468cae276e120e158cd14df5a
work/ice/RESTART/iced.18540101:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ice/iced.18540101
  hashes:
    binhash: c907adec0d9a2f301373b9571ba71610
    md5: ca5237e3542078bb26d93a091cd3280d
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ice/input_ice.nml
  hashes:
    binhash: 609de7606693c7063db6b202773cabcf
    md5: 2c61821a658df9aedbf60919ba4e41ec
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ice/mice.nc
  hashes:
    binhash: 46891a24217273eb71c6cf1ed48b58a1
    md5: c663f3b180337837e871ec061d646b50
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ocean/csiro_bgc.res.nc
  hashes:
    binhash: 11ec60d9f4b07528b84e51429469453e
    md5: e4f66c1451f4bd348a4f451a953a7ce6
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 2523a61fecc1eb4c496dec3b592ee130
    md5: ae7cf0b03343e23f012437e40e79f88b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ocean/ocean_age.res.nc
  hashes:
    binhash: cbf7588b9969735d983b213ea8e233a8
    md5: 91eaafaebe9108e863bf359bc286e1b0
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f0157e62de5f7241317b332caa3507bf
    md5: 40f0b9c1a7f52c38df88b3f41dda4c5d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 51ab8aa1b37f73f9ab1dda3cd426bd0e
    md5: be183ce091da2a806343026b0ea07e23
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ocean/ocean_density.res.nc
  hashes:
    binhash: 28e244f5ed77262b526accffcd2390aa
    md5: 8e4fe8b5bf2561ccddef2974e604a484
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2bd237fadb5100f551ab7fb83c10b53a
    md5: 5b937b562e98d20243a68c1ae3d2002c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 15f4059ce6fbcb54d1a4888c585aec2b
    md5: 0609eabf5dee659a4b92e2a37cdeb194
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 11aec3795e200afe078fe7886ac9249b
    md5: 09046992a239005f5df119053a58feb6
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 80bcb06c30c13103d7eba2a55bdef532
    md5: 415f34c13802cbc142ef170ed2a0eeaa
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 9c01e2bb2852d2f7711cb04b2f8323c6
    md5: 16b9bedad0bb4754818a6a784e676874
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c1122d20579bfc1a168f4128ecdf2b56
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ocean/ocean_solo.res
  hashes:
    binhash: 5422cc4feeb71fc3f0de5e4615fbbd57
    md5: 51441ed419849aae08043a789718f792
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 528bc9a3de7a35903b086dda91138a98
    md5: bd22a494d8d820c62993a9c3fdf9c2db
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ba6f2a77c512e4995e5c6a9218df6252
    md5: ac71cb5c2c6d22623b90798c0467069f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ocean/ocean_tracer.res
  hashes:
    binhash: f4798f6887838b3b4947d86a348184c8
    md5: 3a07c996e7aa3dd4c9deac2dc4616143
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5e4a3a2ad8ff416c6be475c05f6fc1c6
    md5: 588b64e325f5dd8b3eebada2a86a7693
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart004/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 24bd68170025bde2a433000680ad777d
    md5: 931a0a227d6ebe7e36922944167854aa
