format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/atmosphere/restart_dump.astart
  hashes:
    binhash: af1d5721388d0bdf7b2094e42091541c
    md5: 5c521a3ea5b04c85ce1db222643ea1ae
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/atmosphere/um.res.yaml
  hashes:
    binhash: 53013db58646fcf33654074c0f0c498a
    md5: cf2c88361b5b0d1f3ff2bd95f8a9d4f5
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/coupler/a2i.nc
  hashes:
    binhash: d7e640e1e6e1c3f62f2d3863947a112d
    md5: a1805b5bb7e8b9cf99ada46f79ebd7f4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/coupler/i2a.nc
  hashes:
    binhash: b4fe73ae9f6c5185b3e23a11e443064d
    md5: 08160902eb7b41aa163228377a2da08b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/coupler/o2i.nc
  hashes:
    binhash: 2c7e071a5d6625d338bbabe50904d827
    md5: 7a419d07128546e65db303aaec3b9cce
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ice/cice_in.nml
  hashes:
    binhash: f4e7b57b70c4bf8984a0805628c4a28a
    md5: 0fd05bdf2ad4b7b135ce5d57f63295d3
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ice/ice.restart_file
  hashes:
    binhash: b8aafa3b8e01b420210075987c96121e
    md5: ee17cc4112f35c15859d83d974bcf10e
work/ice/RESTART/iced.18570201:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ice/iced.18570201
  hashes:
    binhash: 3aeb6e5360c707fbae5fd592162ee473
    md5: 0deeccb27d06509cea02379d3910ac3c
work/ice/RESTART/iced.18570301:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ice/iced.18570301
  hashes:
    binhash: 8506e02b2e2dbcd2be02ae9d17a44d32
    md5: ff66d7235fa917a138b9b9d685a6f8b7
work/ice/RESTART/iced.18570401:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ice/iced.18570401
  hashes:
    binhash: f6554045d0183795fbafd4475982a392
    md5: f4ffd4056eb1a89710a982854e9a66d5
work/ice/RESTART/iced.18570501:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ice/iced.18570501
  hashes:
    binhash: b6581d0e68bbce2d90e0b0a50a27eea1
    md5: 4031f9a39c42e5b25708f01795961990
work/ice/RESTART/iced.18570601:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ice/iced.18570601
  hashes:
    binhash: cb446088d5885c0fa2807596107d6528
    md5: 69679bd1fac7689d6bfb94ec651b2760
work/ice/RESTART/iced.18570701:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ice/iced.18570701
  hashes:
    binhash: 0de08ffad07245228bc2622f2774a059
    md5: 28cff15a6a82fca45332322759ba75e6
work/ice/RESTART/iced.18570801:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ice/iced.18570801
  hashes:
    binhash: 2a1c2bbcaec3971de482327e2f26e863
    md5: 01daa95db4d820257fbe90026e457410
work/ice/RESTART/iced.18570901:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ice/iced.18570901
  hashes:
    binhash: aa83ecd73faa31c65b621f0141251105
    md5: d2b31101ed4946f77550d2b308880ffb
work/ice/RESTART/iced.18571001:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ice/iced.18571001
  hashes:
    binhash: 4147a324f29b5c55b0a89ad17f489c33
    md5: 37f0076272cf2ee8dc4ff112facc7b48
work/ice/RESTART/iced.18571101:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ice/iced.18571101
  hashes:
    binhash: 739b5633c03dc76c9ed95b3cd3b4d319
    md5: 9664edd5d38734f02e78de06307de9fc
work/ice/RESTART/iced.18571201:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ice/iced.18571201
  hashes:
    binhash: 9685bf4c6e7543c4162fdaaeb8e89caf
    md5: 106b8cd38a8075009cd72f3474ed5cec
work/ice/RESTART/iced.18580101:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ice/iced.18580101
  hashes:
    binhash: c8d31d958992534491dcfb9a6f73fce5
    md5: e58f4967a7962c49aa8de64f2d7ad276
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ice/input_ice.nml
  hashes:
    binhash: 30faa0c93d828bcbdb56dfba9396b05c
    md5: 90ee8e3c76b035b1f52db3193b5db6b5
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ice/mice.nc
  hashes:
    binhash: a403ce4ffbc8f31a2f04610d244d8a1a
    md5: 9ea19c2f9ae8879387620f72e136f8a4
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ocean/csiro_bgc.res.nc
  hashes:
    binhash: 580305c2530129daa9c0b3cc80f4af16
    md5: c1e070e5687872c9aa270daf79734585
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: efa2448d03fc63ec8df2b67c3cd69db6
    md5: 9e4a4ad01b231ca6868e5b022ed1af07
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ocean/ocean_age.res.nc
  hashes:
    binhash: 39a953c9c2b73b5e8ee4df40040af0d6
    md5: 33c6d68b457f71a52419df5d7b317c77
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e56477785ac40c67b332c251f1643de8
    md5: c640de0edc5fe36c70616729237b86dd
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f3e87eb7d4035f03d9a4200f5d5a3780
    md5: 16b494bd38d757bbd0ceb35b8c496e3a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ocean/ocean_density.res.nc
  hashes:
    binhash: a249f147e508e941486ba90988e729a0
    md5: dff61e932c5efe56ca9d0ddf3bcb3394
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1b904b3aa5d2c50de1fa34bba580c199
    md5: cb024af721e5a670ff84a1682c51d48a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 8bdde726a9ad5c89c031bb4d61444e5c
    md5: 072a60f2eca3097860d407cd5e0576e8
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 36ccc98a2f3dc6ae654170bb7c29ff5c
    md5: 4be884c14f0f6ff11a46b830240595f3
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5837e9d74581a02768e41fb4ac43198e
    md5: c3b2be2f472456c5ee232ba0a53788f3
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 6362ab73f20b2934af90499c59cecfdc
    md5: 1631cad309605e4ac98c6ba9355c9ba7
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: dfe5644e098ecafa45d9fa87faf68c18
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ocean/ocean_solo.res
  hashes:
    binhash: 597c31c88746b620225cc274949a7ef5
    md5: 12afd34b7ba983df3e909c9ed242a5c3
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ba6840d5a7780216d6e9a9bdfb40e045
    md5: 256cf6186cbff577051511739211645b
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 26c83c951d905e3fec73c7d0a8762e6a
    md5: 8a6eddc553537c389efd69216e18b6b5
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ocean/ocean_tracer.res
  hashes:
    binhash: e364d314b68cbd9151395eda0e287aa5
    md5: 95f06d20c3c8e66f830f2c96fc706d58
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 1e0c6a6e817aedf23d9f2fe2a529338e
    md5: 0fcf8158b829c0b51cda2df55037bd56
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart008/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: b69cda49895b8e9e7436aace2466cc3e
    md5: 61e96f5a2f0b0748447c16d94fabe45a
