format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/atmosphere/restart_dump.astart
  hashes:
    binhash: 7985be65453c9fcd209297ba9c2b61fb
    md5: cae96cfe73decf8c5dc05965d8b752f8
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/atmosphere/um.res.yaml
  hashes:
    binhash: 7e6268dd6149701ec6be56d127550e7c
    md5: c758713281b32f6444ce7625c36cee56
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/coupler/a2i.nc
  hashes:
    binhash: fff5966ca470fc410db6456ae3093a67
    md5: 25f39c3fb1469327860e516f6998d72c
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/coupler/i2a.nc
  hashes:
    binhash: d0ab97f1b70d3047bd9c73ee817b4870
    md5: e8368285a16389f854faa659ed2cb342
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/coupler/o2i.nc
  hashes:
    binhash: de3ea852e76be9cfbded4543ba7a14ff
    md5: c0a2c2c056ce61eea0f26358b7f0c317
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ice/cice_in.nml
  hashes:
    binhash: 8c9d11ea0089a7343a5746a6d21918d0
    md5: c1f771c7e9dcc47694c36aaf77285163
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ice/ice.restart_file
  hashes:
    binhash: 70f034ff051d7f25a6d2d6f8e3668b2b
    md5: b09bdf1c0e6159f863bf71e077f2f681
work/ice/RESTART/iced.18590201:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ice/iced.18590201
  hashes:
    binhash: 68c0971f708cc31189ac7b2cb06f33cf
    md5: ea95ec368b0ccf7a127f176291356a1f
work/ice/RESTART/iced.18590301:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ice/iced.18590301
  hashes:
    binhash: e7aac63756caada0dc6b886f7c6dafb7
    md5: d6ad45eeb3649702464c8a0020a9a1e4
work/ice/RESTART/iced.18590401:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ice/iced.18590401
  hashes:
    binhash: 1ccc78e02e463467ea48156d9f611953
    md5: 7d8691ff1aac37300a02cd1a23379a15
work/ice/RESTART/iced.18590501:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ice/iced.18590501
  hashes:
    binhash: 3447a5e8715d343ba8289b431066a098
    md5: 43b21fcee1118e6b70f7690244eaeeec
work/ice/RESTART/iced.18590601:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ice/iced.18590601
  hashes:
    binhash: df3adcf3e349261c8d9a19f467032c8c
    md5: 6c89b4c59e1f2b05c78a03ff622f8baa
work/ice/RESTART/iced.18590701:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ice/iced.18590701
  hashes:
    binhash: 5dcb73957ce250d5e809bdf88ccbb0dc
    md5: 717a1bc41b2fc400fe9d3d9eb4054d7e
work/ice/RESTART/iced.18590801:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ice/iced.18590801
  hashes:
    binhash: 2e2561744ad1cf0f1bc687d60e130d2c
    md5: c40a63f704c21e5e819d16092fc59f12
work/ice/RESTART/iced.18590901:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ice/iced.18590901
  hashes:
    binhash: c7a1b31cf91a862db9e9f782dc7843bb
    md5: 4125dec57cbcf3af5c62256804047272
work/ice/RESTART/iced.18591001:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ice/iced.18591001
  hashes:
    binhash: c5fcc9d8b760383e48d343c7028e8850
    md5: a25ffb590ea0b95037b075be4b135b76
work/ice/RESTART/iced.18591101:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ice/iced.18591101
  hashes:
    binhash: 4f844876f9b82c00b56ce1b869ef5edc
    md5: 953a9d66a68bd7512ed59bb62153a608
work/ice/RESTART/iced.18591201:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ice/iced.18591201
  hashes:
    binhash: 410f7393fb45dc1c92cd806e0d3603e3
    md5: cbe17e2e7fb0d71e4eb28481e1d5210d
work/ice/RESTART/iced.18600101:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ice/iced.18600101
  hashes:
    binhash: 0962e6f5e454a7dd0479c2d8eabe57e1
    md5: d0bac958e2615fa517108423b68e7aae
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ice/input_ice.nml
  hashes:
    binhash: 763fd7d925e5937964f9a59c7d5e331b
    md5: 912098d1403953212981dc7acb0d0e32
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ice/mice.nc
  hashes:
    binhash: 11db611bfc503fad8914f66e460a4487
    md5: 0567a49885265fc064c949258261b942
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ocean/csiro_bgc.res.nc
  hashes:
    binhash: e279ee8ab1f751ae708b8c7c7fbd4df4
    md5: 06141524dbf70093a51b4ba0451cf226
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 5c1b3f65f56712923fbe7bbeebfa9abe
    md5: 3c551fcf447ec273aea90428ac8d5c6d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ocean/ocean_age.res.nc
  hashes:
    binhash: aeea2bed80e39840ee4cca894e1160fd
    md5: b51f0170f0a79fe6be0bddba2f00bc52
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: fe724f63ee84efafa88571ed81eaa2f0
    md5: 87dcceb31fb1d67c656d6e8ab8574508
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 666b18e4aa39c8d739cb1500a65fb988
    md5: 5d4df5bed238e044d6413582b5ca65b7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ocean/ocean_density.res.nc
  hashes:
    binhash: e90a4d0284f02e360edd2105b9b7155a
    md5: f9c059c0807a41b6b89ace7ec6a08b64
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 55adb20b1e55a765796f91a529293aad
    md5: fd1d958b2efc9d1554d23c825b1e54c0
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f3cb1b4e609671e75839467f6023c1ed
    md5: 18e9e55a22e3be78dccca078a2dd38e1
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 207d6a5044eab6a884a9f90eb3984d64
    md5: d99404ff10d3e363d9aa1c44b0980f63
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 92b032dba3db61dfd42cd0f252e330b9
    md5: fd414d7f710f3e28dd810a6ab2b21220
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ocean/ocean_sbc.res.nc
  hashes:
    binhash: b1d95ffb688bcd31afdfb5ea022b9ef8
    md5: bfbcad3d92a39819de97977e439189ff
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 1d223c3c506cb00ef06ac7e46af71667
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ocean/ocean_solo.res
  hashes:
    binhash: 1ca927536dcfe6a8cdaf02c2169c22ab
    md5: 8eb98bb713b0a9cf3cfab1ec6e08ce82
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e887123476dceba9426735184a3b7fff
    md5: 8a5709c8753b997dfa30f4d961dac518
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 9c98e16e21bb10a808cd8df00d70a624
    md5: 5e32f7d48ab62857d5c6f1486ecf3670
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ocean/ocean_tracer.res
  hashes:
    binhash: ea5ffad38d6d8a04112d02bf0e09620b
    md5: 0974bed6965c4c8cf7e7b6a4141f2f76
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a09f1a956db4a20f684f99dd06fa34d1
    md5: 68f2fa4ec40444228afd93f721f2c369
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-historical-thinning/restart010/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 1c428b05290879352e4e754f40130caa
    md5: 6b8d526a736e3f3b8f79d0f63d7565d2
